apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "accumulo.fullname" . }}-ts
  labels:
    app: {{ template "accumulo.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: accumulo-ts
spec:
  selector:
    matchLabels:
      app: {{ template "accumulo.name" . }}
  serviceName: {{ template "accumulo.fullname" . }}-ts-svc
  replicas: {{ .Values.accumulo.tserver.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "accumulo.name" . }}
        release: {{ .Release.Name }}
        component: accumulo-ts
    spec:
      dnsConfig:
        searches:
        - {{ template "accumulo.fullname" . }}-manager-svc.accumulo.svc.cluster.local
        - {{ template "accumulo.fullname" . }}-ts-svc.accumulo.svc.cluster.local
      affinity:
      terminationGracePeriodSeconds: 0
      initContainers:
      - name: accumulo-ts-wait
        image: bash
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
        - "/usr/local/bin/bash"
        - "/tmp/accumulo-config/ts-wait.sh"
        resources:
          requests:
            memory: 256Mi
            cpu: 0.5
        volumeMounts:
          - name: accumulo-config
            mountPath: /tmp/accumulo-config
      containers:
      - name: accumulo-ts
        image: {{ .Values.accumuloImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: AWS_ACCESS_KEY_ID
          value: {{ .Values.s3.key }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ .Values.s3.secret }}
        command:
        - "/bin/bash"
        - "/tmp/accumulo-config/tserver.sh"
        resources:
{{ toYaml .Values.accumulo.tserver.resources | indent 10 }}
        volumeMounts:
        - name: accumulo-config
          mountPath: /tmp/accumulo-config
      volumes:
      - name: accumulo-config
        configMap:
          name: accumulo-configmap