# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ template "accumulo.fullname" . }}-monitor-svc
  labels:
    app: {{ template "accumulo.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: accumulo-monitor
spec:
  clusterIP: "None"
  ports:
    - name: http-monitor
      protocol: TCP
      port: 9995
      targetPort: 9995
  selector:
    app: {{ template "accumulo.name" . }}
    release: {{ .Release.Name }}
    component: accumulo-monitor