# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ template "accumulo.fullname" . }}-gc-svc
  labels:
    app: {{ template "accumulo.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: accumulo-gc
spec:
  clusterIP: "None"
  ports:
    - name: accumulo-gc
      protocol: TCP
      port: 9998
      targetPort: 9998
#    - name: tracer
#      protocol: TCP
#      port: 12234
#      targetPort: 12234
  selector:
    app: {{ template "accumulo.name" . }}
    release: {{ .Release.Name }}
    component: accumulo-gc