apiVersion: v1
kind: ConfigMap
metadata:
  name: intg-test-configmap
data:
  AWS_ACCESS_KEY: KEY
  AWS_SECRET_KEY: SECRET
  run.sh: |
    wget "$REPO_LINK"
    unzip "$REPO_BRANCH.zip"
    cd $REPO_NAME-$REPO_BRANCH
    mvn integration-test -DskipITs=false